metadata_dir = "/tmp/meta"
data_dir = "/tmp/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "19a8948f6cbf210b251ae4aa51dfb3b0a4c60482f2fb22939766de19eddb6460"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "ox5O76kqonlCcpBdWdSdgtTdHQcdC5n+fSxXVxYGNJ4="
metrics_token = "PkuFOcWhsgNz9tknTZPgorUa0K+v3TpZVq8b92Lgfe8="
