// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CertificationCenterCreate
 */
export type CertificationCenterCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * CertificationCenterPublic
 */
export type CertificationCenterPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * CertificationCenterUpdate
 */
export type CertificationCenterUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * CertificationCentersPublic
 */
export type CertificationCentersPublic = {
    /**
     * Data
     */
    data: Array<CertificationCenterPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ElectronicDigitalSignatureCreate
 */
export type ElectronicDigitalSignatureCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * ElectronicDigitalSignaturePublic
 */
export type ElectronicDigitalSignaturePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * ElectronicDigitalSignatureUpdate
 */
export type ElectronicDigitalSignatureUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * ElectronicDigitalSignaturesPublic
 */
export type ElectronicDigitalSignaturesPublic = {
    /**
     * Data
     */
    data: Array<ElectronicDigitalSignaturePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * EmployeeCreate
 */
export type EmployeeCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Position
     */
    position: string;
    /**
     * Organization Id
     */
    organization_id: string;
};

/**
 * EmployeePublic
 */
export type EmployeePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Position
     */
    position: string;
    /**
     * Id
     */
    id: string;
    owner: UserPublic;
    organization: OrganizationPublic;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * EmployeeUpdate
 */
export type EmployeeUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Position
     */
    position?: string | null;
};

/**
 * EmployeesPublic
 */
export type EmployeesPublic = {
    /**
     * Data
     */
    data: Array<EmployeePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * OrganizationCreate
 */
export type OrganizationCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * OrganizationPublic
 */
export type OrganizationPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    owner: UserPublic;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * OrganizationUpdate
 */
export type OrganizationUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * OrganizationsPublic
 */
export type OrganizationsPublic = {
    /**
     * Data
     */
    data: Array<OrganizationPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * SignatureTypeCreate
 */
export type SignatureTypeCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * SignatureTypePublic
 */
export type SignatureTypePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * SignatureTypeUpdate
 */
export type SignatureTypeUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * SignatureTypesPublic
 */
export type SignatureTypesPublic = {
    /**
     * Data
     */
    data: Array<SignatureTypePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type organizationsReadOrganizationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/organizations/';
};

export type organizationsReadOrganizationsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type organizationsReadOrganizationsError = organizationsReadOrganizationsErrors[keyof organizationsReadOrganizationsErrors];

export type organizationsReadOrganizationsResponses = {
    /**
     * Successful Response
     */
    200: OrganizationsPublic;
};

export type organizationsReadOrganizationsResponse = organizationsReadOrganizationsResponses[keyof organizationsReadOrganizationsResponses];

export type organizationsCreateOrganizationData = {
    body: OrganizationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/';
};

export type organizationsCreateOrganizationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type organizationsCreateOrganizationError = organizationsCreateOrganizationErrors[keyof organizationsCreateOrganizationErrors];

export type organizationsCreateOrganizationResponses = {
    /**
     * Successful Response
     */
    200: OrganizationPublic;
};

export type organizationsCreateOrganizationResponse = organizationsCreateOrganizationResponses[keyof organizationsCreateOrganizationResponses];

export type organizationsDeleteOrganizationData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}';
};

export type organizationsDeleteOrganizationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type organizationsDeleteOrganizationError = organizationsDeleteOrganizationErrors[keyof organizationsDeleteOrganizationErrors];

export type organizationsDeleteOrganizationResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type organizationsDeleteOrganizationResponse = organizationsDeleteOrganizationResponses[keyof organizationsDeleteOrganizationResponses];

export type organizationsReadOrganizationData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}';
};

export type organizationsReadOrganizationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type organizationsReadOrganizationError = organizationsReadOrganizationErrors[keyof organizationsReadOrganizationErrors];

export type organizationsReadOrganizationResponses = {
    /**
     * Successful Response
     */
    200: OrganizationPublic;
};

export type organizationsReadOrganizationResponse = organizationsReadOrganizationResponses[keyof organizationsReadOrganizationResponses];

export type organizationsUpdateOrganizationData = {
    body: OrganizationUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}';
};

export type organizationsUpdateOrganizationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type organizationsUpdateOrganizationError = organizationsUpdateOrganizationErrors[keyof organizationsUpdateOrganizationErrors];

export type organizationsUpdateOrganizationResponses = {
    /**
     * Successful Response
     */
    200: OrganizationPublic;
};

export type organizationsUpdateOrganizationResponse = organizationsUpdateOrganizationResponses[keyof organizationsUpdateOrganizationResponses];

export type certificationCentersReadCertificationCentersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/certification-centers/';
};

export type certificationCentersReadCertificationCentersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type certificationCentersReadCertificationCentersError = certificationCentersReadCertificationCentersErrors[keyof certificationCentersReadCertificationCentersErrors];

export type certificationCentersReadCertificationCentersResponses = {
    /**
     * Successful Response
     */
    200: CertificationCentersPublic;
};

export type certificationCentersReadCertificationCentersResponse = certificationCentersReadCertificationCentersResponses[keyof certificationCentersReadCertificationCentersResponses];

export type certificationCentersCreateCertificationCenterData = {
    body: CertificationCenterCreate;
    path?: never;
    query?: never;
    url: '/api/v1/certification-centers/';
};

export type certificationCentersCreateCertificationCenterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type certificationCentersCreateCertificationCenterError = certificationCentersCreateCertificationCenterErrors[keyof certificationCentersCreateCertificationCenterErrors];

export type certificationCentersCreateCertificationCenterResponses = {
    /**
     * Successful Response
     */
    200: CertificationCenterPublic;
};

export type certificationCentersCreateCertificationCenterResponse = certificationCentersCreateCertificationCenterResponses[keyof certificationCentersCreateCertificationCenterResponses];

export type certificationCentersDeleteCertificationCenterData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/certification-centers/{id}';
};

export type certificationCentersDeleteCertificationCenterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type certificationCentersDeleteCertificationCenterError = certificationCentersDeleteCertificationCenterErrors[keyof certificationCentersDeleteCertificationCenterErrors];

export type certificationCentersDeleteCertificationCenterResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type certificationCentersDeleteCertificationCenterResponse = certificationCentersDeleteCertificationCenterResponses[keyof certificationCentersDeleteCertificationCenterResponses];

export type certificationCentersReadCertificationCenterData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/certification-centers/{id}';
};

export type certificationCentersReadCertificationCenterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type certificationCentersReadCertificationCenterError = certificationCentersReadCertificationCenterErrors[keyof certificationCentersReadCertificationCenterErrors];

export type certificationCentersReadCertificationCenterResponses = {
    /**
     * Successful Response
     */
    200: CertificationCenterPublic;
};

export type certificationCentersReadCertificationCenterResponse = certificationCentersReadCertificationCenterResponses[keyof certificationCentersReadCertificationCenterResponses];

export type certificationCentersUpdateCertificationCenterData = {
    body: CertificationCenterUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/certification-centers/{id}';
};

export type certificationCentersUpdateCertificationCenterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type certificationCentersUpdateCertificationCenterError = certificationCentersUpdateCertificationCenterErrors[keyof certificationCentersUpdateCertificationCenterErrors];

export type certificationCentersUpdateCertificationCenterResponses = {
    /**
     * Successful Response
     */
    200: CertificationCenterPublic;
};

export type certificationCentersUpdateCertificationCenterResponse = certificationCentersUpdateCertificationCenterResponses[keyof certificationCentersUpdateCertificationCenterResponses];

export type electronicDigitalSignaturesReadElectronicDigitalSignaturesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/electronic-digital-signatures/';
};

export type electronicDigitalSignaturesReadElectronicDigitalSignaturesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type electronicDigitalSignaturesReadElectronicDigitalSignaturesError = electronicDigitalSignaturesReadElectronicDigitalSignaturesErrors[keyof electronicDigitalSignaturesReadElectronicDigitalSignaturesErrors];

export type electronicDigitalSignaturesReadElectronicDigitalSignaturesResponses = {
    /**
     * Successful Response
     */
    200: ElectronicDigitalSignaturesPublic;
};

export type electronicDigitalSignaturesReadElectronicDigitalSignaturesResponse = electronicDigitalSignaturesReadElectronicDigitalSignaturesResponses[keyof electronicDigitalSignaturesReadElectronicDigitalSignaturesResponses];

export type electronicDigitalSignaturesCreateElectronicDigitalSignatureData = {
    body: ElectronicDigitalSignatureCreate;
    path?: never;
    query?: never;
    url: '/api/v1/electronic-digital-signatures/';
};

export type electronicDigitalSignaturesCreateElectronicDigitalSignatureErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type electronicDigitalSignaturesCreateElectronicDigitalSignatureError = electronicDigitalSignaturesCreateElectronicDigitalSignatureErrors[keyof electronicDigitalSignaturesCreateElectronicDigitalSignatureErrors];

export type electronicDigitalSignaturesCreateElectronicDigitalSignatureResponses = {
    /**
     * Successful Response
     */
    200: ElectronicDigitalSignaturePublic;
};

export type electronicDigitalSignaturesCreateElectronicDigitalSignatureResponse = electronicDigitalSignaturesCreateElectronicDigitalSignatureResponses[keyof electronicDigitalSignaturesCreateElectronicDigitalSignatureResponses];

export type electronicDigitalSignaturesDeleteElectronicDigitalSignatureData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/electronic-digital-signatures/{id}';
};

export type electronicDigitalSignaturesDeleteElectronicDigitalSignatureErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type electronicDigitalSignaturesDeleteElectronicDigitalSignatureError = electronicDigitalSignaturesDeleteElectronicDigitalSignatureErrors[keyof electronicDigitalSignaturesDeleteElectronicDigitalSignatureErrors];

export type electronicDigitalSignaturesDeleteElectronicDigitalSignatureResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type electronicDigitalSignaturesDeleteElectronicDigitalSignatureResponse = electronicDigitalSignaturesDeleteElectronicDigitalSignatureResponses[keyof electronicDigitalSignaturesDeleteElectronicDigitalSignatureResponses];

export type electronicDigitalSignaturesReadElectronicDigitalSignatureData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/electronic-digital-signatures/{id}';
};

export type electronicDigitalSignaturesReadElectronicDigitalSignatureErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type electronicDigitalSignaturesReadElectronicDigitalSignatureError = electronicDigitalSignaturesReadElectronicDigitalSignatureErrors[keyof electronicDigitalSignaturesReadElectronicDigitalSignatureErrors];

export type electronicDigitalSignaturesReadElectronicDigitalSignatureResponses = {
    /**
     * Successful Response
     */
    200: ElectronicDigitalSignaturePublic;
};

export type electronicDigitalSignaturesReadElectronicDigitalSignatureResponse = electronicDigitalSignaturesReadElectronicDigitalSignatureResponses[keyof electronicDigitalSignaturesReadElectronicDigitalSignatureResponses];

export type electronicDigitalSignaturesUpdateElectronicDigitalSignatureData = {
    body: ElectronicDigitalSignatureUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/electronic-digital-signatures/{id}';
};

export type electronicDigitalSignaturesUpdateElectronicDigitalSignatureErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type electronicDigitalSignaturesUpdateElectronicDigitalSignatureError = electronicDigitalSignaturesUpdateElectronicDigitalSignatureErrors[keyof electronicDigitalSignaturesUpdateElectronicDigitalSignatureErrors];

export type electronicDigitalSignaturesUpdateElectronicDigitalSignatureResponses = {
    /**
     * Successful Response
     */
    200: ElectronicDigitalSignaturePublic;
};

export type electronicDigitalSignaturesUpdateElectronicDigitalSignatureResponse = electronicDigitalSignaturesUpdateElectronicDigitalSignatureResponses[keyof electronicDigitalSignaturesUpdateElectronicDigitalSignatureResponses];

export type employeesReadEmployeesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/employees/';
};

export type employeesReadEmployeesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type employeesReadEmployeesError = employeesReadEmployeesErrors[keyof employeesReadEmployeesErrors];

export type employeesReadEmployeesResponses = {
    /**
     * Successful Response
     */
    200: EmployeesPublic;
};

export type employeesReadEmployeesResponse = employeesReadEmployeesResponses[keyof employeesReadEmployeesResponses];

export type employeesCreateEmployeeData = {
    body: EmployeeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/employees/';
};

export type employeesCreateEmployeeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type employeesCreateEmployeeError = employeesCreateEmployeeErrors[keyof employeesCreateEmployeeErrors];

export type employeesCreateEmployeeResponses = {
    /**
     * Successful Response
     */
    200: EmployeePublic;
};

export type employeesCreateEmployeeResponse = employeesCreateEmployeeResponses[keyof employeesCreateEmployeeResponses];

export type employeesDeleteEmployeeData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/employees/{id}';
};

export type employeesDeleteEmployeeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type employeesDeleteEmployeeError = employeesDeleteEmployeeErrors[keyof employeesDeleteEmployeeErrors];

export type employeesDeleteEmployeeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type employeesDeleteEmployeeResponse = employeesDeleteEmployeeResponses[keyof employeesDeleteEmployeeResponses];

export type employeesReadEmployeeData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/employees/{id}';
};

export type employeesReadEmployeeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type employeesReadEmployeeError = employeesReadEmployeeErrors[keyof employeesReadEmployeeErrors];

export type employeesReadEmployeeResponses = {
    /**
     * Successful Response
     */
    200: EmployeePublic;
};

export type employeesReadEmployeeResponse = employeesReadEmployeeResponses[keyof employeesReadEmployeeResponses];

export type employeesUpdateEmployeeData = {
    body: EmployeeUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/employees/{id}';
};

export type employeesUpdateEmployeeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type employeesUpdateEmployeeError = employeesUpdateEmployeeErrors[keyof employeesUpdateEmployeeErrors];

export type employeesUpdateEmployeeResponses = {
    /**
     * Successful Response
     */
    200: EmployeePublic;
};

export type employeesUpdateEmployeeResponse = employeesUpdateEmployeeResponses[keyof employeesUpdateEmployeeResponses];

export type signatureTypesReadSignatureTypesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/signature-types/';
};

export type signatureTypesReadSignatureTypesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type signatureTypesReadSignatureTypesError = signatureTypesReadSignatureTypesErrors[keyof signatureTypesReadSignatureTypesErrors];

export type signatureTypesReadSignatureTypesResponses = {
    /**
     * Successful Response
     */
    200: SignatureTypesPublic;
};

export type signatureTypesReadSignatureTypesResponse = signatureTypesReadSignatureTypesResponses[keyof signatureTypesReadSignatureTypesResponses];

export type signatureTypesCreateSignatureTypeData = {
    body: SignatureTypeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/signature-types/';
};

export type signatureTypesCreateSignatureTypeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type signatureTypesCreateSignatureTypeError = signatureTypesCreateSignatureTypeErrors[keyof signatureTypesCreateSignatureTypeErrors];

export type signatureTypesCreateSignatureTypeResponses = {
    /**
     * Successful Response
     */
    200: SignatureTypePublic;
};

export type signatureTypesCreateSignatureTypeResponse = signatureTypesCreateSignatureTypeResponses[keyof signatureTypesCreateSignatureTypeResponses];

export type signatureTypesDeleteSignatureTypeData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/signature-types/{id}';
};

export type signatureTypesDeleteSignatureTypeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type signatureTypesDeleteSignatureTypeError = signatureTypesDeleteSignatureTypeErrors[keyof signatureTypesDeleteSignatureTypeErrors];

export type signatureTypesDeleteSignatureTypeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type signatureTypesDeleteSignatureTypeResponse = signatureTypesDeleteSignatureTypeResponses[keyof signatureTypesDeleteSignatureTypeResponses];

export type signatureTypesReadSignatureTypeData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/signature-types/{id}';
};

export type signatureTypesReadSignatureTypeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type signatureTypesReadSignatureTypeError = signatureTypesReadSignatureTypeErrors[keyof signatureTypesReadSignatureTypeErrors];

export type signatureTypesReadSignatureTypeResponses = {
    /**
     * Successful Response
     */
    200: SignatureTypePublic;
};

export type signatureTypesReadSignatureTypeResponse = signatureTypesReadSignatureTypeResponses[keyof signatureTypesReadSignatureTypeResponses];

export type signatureTypesUpdateSignatureTypeData = {
    body: SignatureTypeUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/signature-types/{id}';
};

export type signatureTypesUpdateSignatureTypeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type signatureTypesUpdateSignatureTypeError = signatureTypesUpdateSignatureTypeErrors[keyof signatureTypesUpdateSignatureTypeErrors];

export type signatureTypesUpdateSignatureTypeResponses = {
    /**
     * Successful Response
     */
    200: SignatureTypePublic;
};

export type signatureTypesUpdateSignatureTypeResponse = signatureTypesUpdateSignatureTypeResponses[keyof signatureTypesUpdateSignatureTypeResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
