# Generated by Django 5.2.1 on 2025-07-06 11:20

import apps.employees.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], help_text='Выберите пол', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='inn',
            field=models.OneToOneField(blank=True, help_text='Выберите ИНН', null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.inn', verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Введите имя', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport',
            field=models.OneToOneField(blank=True, help_text='Выберите паспорт', null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.passport', verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(help_text='Введите отчество', max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='snils',
            field=models.OneToOneField(blank=True, help_text='Выберите СНИЛС', null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.snils', verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(help_text='Введите фамилию', max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='inn',
            name='value',
            field=models.CharField(help_text='Введите ИНН', max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='birthdate',
            field=models.DateField(help_text='Введите дату рождения', validators=[apps.employees.validators.validate_birthdate], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='birthplace',
            field=models.CharField(help_text='Введите место рождения', max_length=200, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='code',
            field=models.CharField(help_text='Введите код подразделения', max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='Формат: 000-000', regex='^\\d{3}-\\d{3}$')], verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_of_issue',
            field=models.DateField(help_text='Введите дату выдачи паспорта', verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(help_text='Введите номер паспорта', max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.CharField(help_text='Введите серию паспорта', max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='snils',
            name='value',
            field=models.CharField(help_text='Введите СНИЛС', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='СНИЛС'),
        ),
    ]
