# Generated by Django 5.2.1 on 2025-07-06 11:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(help_text='Введите идентификационный номер налогоплательщика', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kpp',
            field=models.CharField(help_text='Введите код причины постановки на учёт', max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Введите название организации', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(help_text='Введите основной государственный регистрационный номер', max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registered_address',
            field=models.CharField(help_text='Введите юридический адрес', max_length=200, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(help_text='Введите название должности', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='position',
            name='organization',
            field=models.ForeignKey(help_text='Выберите организацию', on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Организация'),
        ),
    ]
