"""Add mixin to Organization model

Revision ID: 1a3b41509b5b
Revises: 341a312a6d50
Create Date: 2026-08-25 21:14:51.197205

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1a3b41509b5b'
down_revision = '341a312a6d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'updated_at')
    # ### end Alembic commands ###
