"""Fix relationship employee

Revision ID: 220053541ad1
Revises: 82b3a2b77d34
Create Date: 2026-08-30 16:22:21.165665

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '220053541ad1'
down_revision = '82b3a2b77d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
