"""Change file's column to EDS model

Revision ID: 3b010a1fecfe
Revises: e55d1be8aa1d
Create Date: 2026-09-05 13:40:28.674296

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b010a1fecfe'
down_revision = 'e55d1be8aa1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('electronicdigitalsignature', 'file_certificate',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('electronicdigitalsignature', 'file_container',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('electronicdigitalsignature', 'file_container',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.alter_column('electronicdigitalsignature', 'file_certificate',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
