"""refactor public model to employee and organization

Revision ID: 5e55b3330f2e
Revises: 220053541ad1
Create Date: 2026-08-30 16:34:07.696798

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5e55b3330f2e'
down_revision = '220053541ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employee_organization_id'), 'employee', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employee_owner_id'), 'employee', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_owner_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_organization_id'), table_name='employee')
    # ### end Alembic commands ###
