"""Add relationship between employee and organization

Revision ID: 80c0f87fd881
Revises: 20764a2f4c4b
Create Date: 2026-08-30 16:15:55.802168

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '80c0f87fd881'
down_revision = '20764a2f4c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('employee', sa.Column('organization_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'employee', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'organization_id')
    op.drop_column('employee', 'position')
    # ### end Alembic commands ###
