"""Fix relationship employee

Revision ID: 82b3a2b77d34
Revises: c4b8dcdff0eb
Create Date: 2026-08-30 16:20:49.196039

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '82b3a2b77d34'
down_revision = 'c4b8dcdff0eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
