"""Fix relationship between employee and organization

Revision ID: c4b8dcdff0eb
Revises: 80c0f87fd881
Create Date: 2026-08-30 16:18:55.570483

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c4b8dcdff0eb'
down_revision = '80c0f87fd881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
