"""Add relationships to EDS model

Revision ID: e55d1be8aa1d
Revises: 5e55b3330f2e
Create Date: 2026-09-03 22:26:09.809332

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e55d1be8aa1d'
down_revision = '5e55b3330f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificationcenter', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('certificationcenter', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('electronicdigitalsignature', sa.Column('date_certificate', sa.DateTime(timezone=True), nullable=False))
    op.add_column('electronicdigitalsignature', sa.Column('file_certificate', sa.LargeBinary(), nullable=True))
    op.add_column('electronicdigitalsignature', sa.Column('date_container', sa.DateTime(timezone=True), nullable=False))
    op.add_column('electronicdigitalsignature', sa.Column('file_container', sa.LargeBinary(), nullable=True))
    op.add_column('electronicdigitalsignature', sa.Column('organization_id', sa.Uuid(), nullable=False))
    op.add_column('electronicdigitalsignature', sa.Column('signature_type_id', sa.Uuid(), nullable=False))
    op.add_column('electronicdigitalsignature', sa.Column('employee_id', sa.Uuid(), nullable=True))
    op.add_column('electronicdigitalsignature', sa.Column('certification_center_id', sa.Uuid(), nullable=False))
    op.alter_column('electronicdigitalsignature', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('electronicdigitalsignature', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_foreign_key(None, 'electronicdigitalsignature', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'electronicdigitalsignature', 'signaturetype', ['signature_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'electronicdigitalsignature', 'certificationcenter', ['certification_center_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'electronicdigitalsignature', 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_column('electronicdigitalsignature', 'name')
    op.alter_column('employee', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('employee', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('organization', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('organization', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('signaturetype', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('signaturetype', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signaturetype', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('signaturetype', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('organization', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('organization', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('employee', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('employee', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('electronicdigitalsignature', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'electronicdigitalsignature', type_='foreignkey')
    op.drop_constraint(None, 'electronicdigitalsignature', type_='foreignkey')
    op.drop_constraint(None, 'electronicdigitalsignature', type_='foreignkey')
    op.drop_constraint(None, 'electronicdigitalsignature', type_='foreignkey')
    op.alter_column('electronicdigitalsignature', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('electronicdigitalsignature', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('electronicdigitalsignature', 'certification_center_id')
    op.drop_column('electronicdigitalsignature', 'employee_id')
    op.drop_column('electronicdigitalsignature', 'signature_type_id')
    op.drop_column('electronicdigitalsignature', 'organization_id')
    op.drop_column('electronicdigitalsignature', 'file_container')
    op.drop_column('electronicdigitalsignature', 'date_container')
    op.drop_column('electronicdigitalsignature', 'file_certificate')
    op.drop_column('electronicdigitalsignature', 'date_certificate')
    op.alter_column('certificationcenter', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('certificationcenter', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
