"""Change field type on EDS model

Revision ID: f95e178d21f4
Revises: fae60d2339c7
Create Date: 2026-09-12 17:00:45.698453

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f95e178d21f4'
down_revision = 'fae60d2339c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('electronicdigitalsignature', 'file_certificate',
               existing_type=postgresql.BYTEA(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1024),
               existing_nullable=False)
    op.alter_column('electronicdigitalsignature', 'file_container',
               existing_type=postgresql.BYTEA(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1024),
               existing_nullable=False)
    op.alter_column('electronicdigitalsignature', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('electronicdigitalsignature', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('electronicdigitalsignature', 'signature_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('electronicdigitalsignature', 'employee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('electronicdigitalsignature', 'certification_center_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('electronicdigitalsignature_signature_type_id_fkey'), 'electronicdigitalsignature', type_='foreignkey')
    op.drop_constraint(op.f('electronicdigitalsignature_owner_id_fkey'), 'electronicdigitalsignature', type_='foreignkey')
    op.drop_constraint(op.f('electronicdigitalsignature_employee_id_fkey'), 'electronicdigitalsignature', type_='foreignkey')
    op.drop_constraint(op.f('electronicdigitalsignature_certification_center_id_fkey'), 'electronicdigitalsignature', type_='foreignkey')
    op.drop_constraint(op.f('electronicdigitalsignature_organization_id_fkey'), 'electronicdigitalsignature', type_='foreignkey')
    op.create_foreign_key(None, 'electronicdigitalsignature', 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'electronicdigitalsignature', 'certificationcenter', ['certification_center_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'electronicdigitalsignature', 'signaturetype', ['signature_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'electronicdigitalsignature', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'electronicdigitalsignature', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'electronicdigitalsignature', type_='foreignkey')
    op.drop_constraint(None, 'electronicdigitalsignature', type_='foreignkey')
    op.drop_constraint(None, 'electronicdigitalsignature', type_='foreignkey')
    op.drop_constraint(None, 'electronicdigitalsignature', type_='foreignkey')
    op.drop_constraint(None, 'electronicdigitalsignature', type_='foreignkey')
    op.create_foreign_key(op.f('electronicdigitalsignature_organization_id_fkey'), 'electronicdigitalsignature', 'organization', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('electronicdigitalsignature_certification_center_id_fkey'), 'electronicdigitalsignature', 'certificationcenter', ['certification_center_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('electronicdigitalsignature_employee_id_fkey'), 'electronicdigitalsignature', 'employee', ['employee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('electronicdigitalsignature_owner_id_fkey'), 'electronicdigitalsignature', 'user', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('electronicdigitalsignature_signature_type_id_fkey'), 'electronicdigitalsignature', 'signaturetype', ['signature_type_id'], ['id'], ondelete='SET NULL')
    op.alter_column('electronicdigitalsignature', 'certification_center_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('electronicdigitalsignature', 'employee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('electronicdigitalsignature', 'signature_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('electronicdigitalsignature', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('electronicdigitalsignature', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('electronicdigitalsignature', 'file_container',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1024),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    op.alter_column('electronicdigitalsignature', 'file_certificate',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1024),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    # ### end Alembic commands ###
