"""Delete relationship employee and organization

Revision ID: fae60d2339c7
Revises: 072ca79ebcd3
Create Date: 2026-09-12 15:44:16.693824

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fae60d2339c7'
down_revision = '072ca79ebcd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_organization_id'), table_name='employee')
    op.drop_constraint(op.f('employee_organization_id_fkey'), 'employee', type_='foreignkey')
    op.drop_column('employee', 'organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('employee_organization_id_fkey'), 'employee', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_employee_organization_id'), 'employee', ['organization_id'], unique=False)
    # ### end Alembic commands ###
