# Generated by Django 5.2.1 on 2025-06-15 11:51

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Удостоверяющий центр',
                'verbose_name_plural': 'Удостоверяющие центры',
            },
        ),
        migrations.CreateModel(
            name='INN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('value', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='ИНН')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'ИНН',
                'verbose_name_plural': 'ИНН',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('ogrn', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='ОГРН')),
                ('inn', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='КПП')),
                ('registered_address', models.CharField(max_length=200, verbose_name='Юридический адрес')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('series', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='Серия')),
                ('number', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='Номер')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('birthplace', models.CharField(max_length=200, verbose_name='Место рождения')),
                ('code', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='Формат: 000-000', regex='^\\d{3}-\\d{3}$')], verbose_name='Код подразделения')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=200, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
                ('inn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.inn', verbose_name='ИНН')),
                ('passport', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.passport', verbose_name='Паспорт')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('filename', models.CharField(max_length=200, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='', validators=[core.validators.validate_file_sertificate], verbose_name='Сертификат')),
                ('start_date', models.DateField(verbose_name='Дата начала действия')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('certification_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.certificationcenter', verbose_name='Удостоверяющий центр')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='ElectronicDigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('filename', models.CharField(max_length=200, verbose_name='Имя файла')),
                ('archive', models.FileField(upload_to='', validators=[core.validators.validate_file_archive], verbose_name='Архив')),
                ('start_date', models.DateField(verbose_name='Дата начала действия')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='core.employee', verbose_name='Владелец')),
                ('sertificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sertificate', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'ЭЦП',
                'verbose_name_plural': 'ЭЦП',
            },
        ),
        migrations.CreateModel(
            name='SNILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('value', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='СНИЛС')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'СНИЛС',
                'verbose_name_plural': 'СНИЛС',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='snils',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.snils', verbose_name='СНИЛС'),
        ),
    ]
