# Generated by Django 5.2.1 on 2025-05-24 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_electronicdigitalsignature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electronicdigitalsignature',
            options={'verbose_name': 'ЭЦП', 'verbose_name_plural': 'ЭЦП'},
        ),
        migrations.AddField(
            model_name='electronicdigitalsignature',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.employee'),
        ),
    ]
