# Generated by Django 5.2.1 on 2025-05-24 14:38

import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_electronicdigitalsignature_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civildocument',
            name='birthdate',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='civildocument',
            name='birthplace',
            field=models.CharField(max_length=200, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='civildocument',
            name='code',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='Формат: 000-000', regex='^\\d{3}-\\d{3}$')], verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='civildocument',
            name='date_of_issue',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='civildocument',
            name='inn',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='civildocument',
            name='number',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='civildocument',
            name='series',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='civildocument',
            name='snils',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='electronicdigitalsignature',
            name='archive',
            field=models.FileField(upload_to='', validators=[core.validators.validate_file_archive], verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='electronicdigitalsignature',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.employee', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='electronicdigitalsignature',
            name='sertificate',
            field=models.FileField(upload_to='', validators=[core.validators.validate_file_sertificate], verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='electronicdigitalsignature',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='civil_document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.civildocument', verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kpp',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registered_address',
            field=models.CharField(max_length=200, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='position',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
