# Generated by Django 5.2.1 on 2025-05-24 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_civildocument_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicdigitalsignature',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.employee', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='civil_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.civildocument', verbose_name='Документы'),
        ),
    ]
