# Generated by Django 5.2.1 on 2025-05-25 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_employee_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='author',
        ),
        migrations.AddField(
            model_name='civildocument',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='civil_document_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='civildocument',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='civil_document_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='civildocument',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='ЧПУ'),
        ),
        migrations.AddField(
            model_name='electronicdigitalsignature',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electronic_digital_signature_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='electronicdigitalsignature',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electronic_digital_signature_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='electronicdigitalsignature',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='ЧПУ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='employee',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='organization',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='ЧПУ'),
        ),
        migrations.AddField(
            model_name='position',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='position',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='ЧПУ'),
        ),
    ]
