# Generated by Django 5.2.1 on 2025-05-26 16:53

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_civildocument_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='civil_document',
        ),
        migrations.AddField(
            model_name='electronicdigitalsignature',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='electronicdigitalsignature',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала действия'),
        ),
        migrations.CreateModel(
            name='INN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='ИНН')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='inn_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='inn_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'ИНН',
                'verbose_name_plural': 'ИНН',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='inn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.inn', verbose_name='ИНН'),
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='Серия')),
                ('number', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='Номер')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('birthplace', models.CharField(max_length=200, verbose_name='Место рождения')),
                ('code', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='Формат: 000-000', regex='^\\d{3}-\\d{3}$')], verbose_name='Код подразделения')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='passport_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='passport_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.passport', verbose_name='Паспорт'),
        ),
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='', validators=[core.validators.validate_file_sertificate], verbose_name='Сертификат')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала действия')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='sertificate_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='sertificate_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.AlterField(
            model_name='electronicdigitalsignature',
            name='sertificate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sertificate', verbose_name='Сертификат'),
        ),
        migrations.CreateModel(
            name='SNILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='СНИЛС')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='snils_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='snils_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'СНИЛС',
                'verbose_name_plural': 'СНИЛС',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='snils',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.snils', verbose_name='СНИЛС'),
        ),
        migrations.DeleteModel(
            name='CivilDocument',
        ),
    ]
