# Generated by Django 5.2.1 on 2025-05-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_electronicdigitalsignature_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicdigitalsignature',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='electronicdigitalsignature',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала действия'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала действия'),
        ),
    ]
