# Generated by Django 5.2.1 on 2025-06-03 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_certificationcenter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronicdigitalsignature',
            old_name='Certification_centerwner',
            new_name='certification_centerwner',
        ),
        migrations.AlterField(
            model_name='certificationcenter',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='certification_center_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='certificationcenter',
            name='modified_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='certification_center_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено'),
        ),
    ]
