# Generated by Django 5.2.1 on 2025-07-13 12:20

import apps.signatures.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_options_alter_employee_gender_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('name', models.CharField(help_text='Введите название удостоверяющего центра', max_length=200, verbose_name='Название')),
                ('inn', models.CharField(help_text='Введите идентификационный номер налогоплательщика удостоверяющего центра', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='ИНН')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Удостоверяющий центр',
                'verbose_name_plural': 'Удостоверяющие центры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('file', models.FileField(help_text='Загрузите файл сертификата', unique=True, upload_to='', validators=[apps.signatures.validators.validate_file_sertificate], verbose_name='Сертификат')),
                ('start_date', models.DateField(help_text='Введите дату начала действия', verbose_name='Дата начала действия')),
                ('end_date', models.DateField(help_text='Введите дату окончания', verbose_name='Дата окончания')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
                ('position', models.ForeignKey(help_text='Выберите должность', on_delete=django.db.models.deletion.PROTECT, to='organizations.position', verbose_name='Должность')),
                ('certification_center', models.ForeignKey(help_text='Выберите удостоверяющий центр', on_delete=django.db.models.deletion.PROTECT, to='signatures.certificationcenter', verbose_name='Удостоверяющий центр')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicDigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='ЧПУ')),
                ('archive', models.FileField(upload_to='', validators=[apps.signatures.validators.validate_file_archive], verbose_name='Архив')),
                ('start_date', models.DateField(help_text='Введите дату начала действия', verbose_name='Дата начала действия')),
                ('end_date', models.DateField(help_text='Введите дату окончания', verbose_name='Дата окончания')),
                ('certificate', models.OneToOneField(blank=True, help_text='Выберите сертификат', null=True, on_delete=django.db.models.deletion.PROTECT, to='signatures.certificate', verbose_name='Сертификат')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменено')),
                ('owner', models.ForeignKey(blank=True, help_text='Выберите владельца', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='employees.employee', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'ЭЦП',
                'verbose_name_plural': 'ЭЦП',
                'ordering': ['end_date'],
            },
        ),
    ]
