# Generated by Django 5.2.1 on 2025-07-06 11:20

import apps.signatures.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_alter_employee_gender_and_more'),
        ('organizations', '0002_alter_organization_inn_alter_organization_kpp_and_more'),
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicdigitalsignature',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='sertificate',
            name='filename',
        ),
        migrations.AlterField(
            model_name='certificationcenter',
            name='inn',
            field=models.CharField(help_text='Введите идентификационный номер налогоплательщика удостоверяющего центра', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Разрешены только цифры.', regex='^\\d+$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='certificationcenter',
            name='name',
            field=models.CharField(help_text='Введите название удостоверяющего центра', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='electronicdigitalsignature',
            name='end_date',
            field=models.DateField(help_text='Введите дату окончания', verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='electronicdigitalsignature',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Выберите владельца', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='employees.employee', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='electronicdigitalsignature',
            name='sertificate',
            field=models.OneToOneField(blank=True, help_text='Выберите сертификат', null=True, on_delete=django.db.models.deletion.PROTECT, to='signatures.sertificate', verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='electronicdigitalsignature',
            name='start_date',
            field=models.DateField(help_text='Введите дату начала действия', verbose_name='Дата начала действия'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='certification_center',
            field=models.ForeignKey(help_text='Выберите удостоверяющий центр', on_delete=django.db.models.deletion.PROTECT, to='signatures.certificationcenter', verbose_name='Удостоверяющий центр'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='end_date',
            field=models.DateField(help_text='Введите дату окончания', verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='file',
            field=models.FileField(help_text='Загрузите файл сертификата', unique=True, upload_to='', validators=[apps.signatures.validators.validate_file_sertificate], verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='position',
            field=models.ForeignKey(help_text='Выберите должность', on_delete=django.db.models.deletion.PROTECT, to='organizations.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='start_date',
            field=models.DateField(help_text='Введите дату начала действия', verbose_name='Дата начала действия'),
        ),
    ]
